//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Login.Datos.DBLogin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class LoginCentralizadoEntities : DbContext
    {
        public LoginCentralizadoEntities()
            : base("name=LoginCentralizadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_AplicativosWebs> Cat_AplicativosWebs { get; set; }
        public virtual DbSet<Cat_Puertos> Cat_Puertos { get; set; }
        public virtual DbSet<Cat_Roles> Cat_Roles { get; set; }
        public virtual DbSet<Cat_Servidores> Cat_Servidores { get; set; }
        public virtual DbSet<R_CatAplicativosWebs_CatServidores> R_CatAplicativosWebs_CatServidores { get; set; }
        public virtual DbSet<R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores> R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_UsuariosWeb> tbl_UsuariosWeb { get; set; }
        public virtual DbSet<tbl_SolicitudesCambioPassword> tbl_SolicitudesCambioPassword { get; set; }
    }
}
