//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Login.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores
    {
        public int Id { get; set; }
        public int Id_UsuarioWeb { get; set; }
        public int Id_Rol { get; set; }
        public int Id_R_CatAplicativosWebs_CatServidores { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cat_Roles Cat_Roles { get; set; }
        public virtual R_CatAplicativosWebs_CatServidores R_CatAplicativosWebs_CatServidores { get; set; }
        public virtual tbl_UsuariosWeb tbl_UsuariosWeb { get; set; }
    }
}
