//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Login.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsuariosWeb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UsuariosWeb()
        {
            this.R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores = new HashSet<R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores>();
        }
    
        public int Id { get; set; }
        public int IdUsuarioAlpha_nomina_nom_cat_user { get; set; }
        public Nullable<System.DateTime> UltimaSesion { get; set; }
        public bool EsRoot { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores> R_UsuariosWebs_CatRol_RCatAplicativosWebsServidores { get; set; }
    }
}
