//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Login.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SolicitudesCambioPassword
    {
        public int Id { get; set; }
        public int IdUsuarioALPHA { get; set; }
        public string SolicitudDesdePC { get; set; }
        public string SolicitudDesdeMAC { get; set; }
        public string SolicitudDesdeIP { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public bool SeUsoFolio { get; set; }
        public bool Activo { get; set; }
    }
}
